server:
    port: 40100
    servlet:
        session:
            cookie:
                max-age: 3600
    tomcat:
        max-threads: 1000
spring:
    datasource:
        druid:
            url: jdbc:mysql://budingcc.cn:3306/bd_user?characterEncoding=utf-8&useSSL=false
            username: buding
            password: buding2019
            driverClassName: com.mysql.jdbc.Driver
            initialSize: 5  #初始建立连接数量
            minIdle: 5  #最小连接数量
            maxActive: 20 #最大连接数量
            maxWait: 10000  #获取连接最大等待时间，毫秒
            testOnBorrow: true #申请连接时检测连接是否有效
            testOnReturn: false #归还连接时检测连接是否有效
            timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
            minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
    application:
        name: buding-service-ucenter
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://budingcc.cn:50000/eureka
    instance:
        prefer-ip-address: true
        ip-address: budingcc.cn
        instance-id: ${spring.application.name}:${server.port}


security:
    oauth2:
        client:
            client-id: ucenterService
            client-secret: 123456
        resource:
            jwt:
                key-uri: http://oauth.budingcc.cn:40000/oauth/token_key


logging:
    level:
        cn:
            budingcc:
                ucenter:
                    dao: debug
