server:
    port: 32000
spring:
    application:
        name: buding-service-socketio
socketio:
    host: budingcc.cn
    port: 32001
    # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
    maxFramePayloadLength: 1048576
    # 设置http交互最大内容长度
    maxHttpContentLength: 1048576
    # socket连接数大小（如只监听一个端口boss线程组为1即可）
    bossCount: 1
    workCount: 100
    allowCustomRequests: true
    # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
    upgradeTimeout: 1000000
    # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
    pingTimeout: 6000000
    # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
    pingInterval: 25000
eureka:
    client:
        service-url:
            defaultZone: http://budingcc.cn:50000/eureka
        register-with-eureka: true
        fetch-registry: true
    instance:
        ip-address: budingcc.cn
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${server.port}