server:
    port: 50000
spring:
    application:
        name: bd-govern-center
eureka:
    client:
        registerWithEureka: false #服务注册，是否将自己注册到Eureka服务中
        fetchRegistry: false #服务发现，是否从Eureka中获取注册信息
        service-url:
            defaultZone: http://budingcc.cn:${server.port}/eureka/
    server:
        enable-self-preservation: false #是否开启自我保护模式
        eviction-interval-timer-in-ms: 60000 #服务注册表清理间隔（单位毫秒，默认是60*1000）
    instance:
        hostname: eureka