server:
    port: 30000
    servlet:
        session:
            cookie:
                max-age: 36000
                name: GATEWAYJSESSIONID
            timeout: 72000
spring:
    application:
        name: buding-service-gateway
    redis:
        password: redis6379
eureka:
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${server.port}
        ip-address: budingcc.cn
    client:
        service-url:
            defaultZone: http://budingcc.cn:50000/eureka
zuul:
    # prefix是不会带上去微服务的
    prefix: /api
    sensitive-headers:
    ratelimit:
        enabled: true
        repository: redis
        default-policy-list:
         - limit: 3
           refresh-interval: 3
           quot: 3
           type:
            - url
    routes:
        buding-service-shop:
            path: /shop/**
            serviceId: buding-service-shop
            strip-prefix: false
        buding-service-ucenter:
            path: /ucenter/**
            serviceId: buding-service-ucenter
            strip-prefix: false
        buding-service-ucenter-auth:
            path: /oauth/**
            serviceId: buding-service-ucenter-auth
            strip-prefix: false
        buding-service-filesystem:
            path: /filesystem/**
            serviceId: buding-service-filesystem
            strip-prefix: false
        buding-service-es:
            path: /es/**
            serviceId: buding-service-es
            strip-prefix: false
        buding-service-cms:
            path: /cms/**
            serviceId: buding-service-cms
            strip-prefix: false
# key uri
security:
    oauth2:
        client:
            client-id: gateway
            client-secret: 123456
        resource:
            jwt:
                key-uri: http://oauth.budingcc.cn:40000/oauth/token_key
logging:
    pattern:
        console: