server:
    port: 40010
    servlet:
        session:
            cookie:
                max-age: 36000
                name: AUTHWEBJSESSIONID
            timeout: 36000

spring:
    application:
        name: buding-auth-web
    redis:
        host: ${REDIS_HOST:127.0.0.1}
        port: ${REDIS_PORT:6379}
        timeout: 5000 #连接超时 毫秒
        jedis:
            pool:
                maxActive: 3
                maxIdle: 3
                minIdle: 1
                maxWait: -1 #连接池最大等行时间 -1没有限制
        password: redis6379
buding:
    auth:
        serverUrl: http://oauth.budingcc.cn:40000
zuul:
    routes:
        api:
            path: /api/**
            url: http://gateway.budingcc.cn:30000
            strip-prefix: false
        oauth:
            path: /oauth/**
            url: forward:/oauth
            strip-prefix: true
    sensitive-headers:
