server:
    port: 31001
    servlet:
        context-path: /shop
spring:
    application:
        name: buding-service-shop
    datasource:
        druid:
            url: jdbc:mysql://budingcc.cn:3306/bd_shop?characterEncoding=utf-8
            username: buding
            password: buding2019
            driverClassName: com.mysql.jdbc.Driver
            initialSize: 5  #初始建立连接数量
            minIdle: 5  #最小连接数量
            maxActive: 20 #最大连接数量
            maxWait: 10000  #获取连接最大等待时间，毫秒
            testOnBorrow: true #申请连接时检测连接是否有效
            testOnReturn: false #归还连接时检测连接是否有效
            timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
            minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
    rabbitmq:
        username: Ikaros
        password: newLife2016
        host: budingcc.cn
        port: 5672
        virtual-host: /
        listener:
            direct:
                prefetch: 1
                acknowledge-mode: auto
eureka:
    client:
        registerWithEureka: true #服务注册开关
        fetchRegistry: true #服务发现开关
        service-url: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
            defaultZone: http://budingcc.cn:50000/eureka/
    instance:
        prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
        ip-address: budingcc.cn
        instance-id: ${spring.application.name}:${server.port} #指定实例id
buding:
    rabbitmq:
        bd_cms_exchange: bd_cms_exchange
security:
    oauth2:
        client:
            client-id: shopService
            client-secret: 123456
        resource:
            jwt:
                key-uri: http://oauth.budingcc.cn:40000/oauth/token_key
feign:
    hystrix:
        enabled: true

