server:
    port: 31000
    jetty:
        max-threads: 1000
spring:
    application:
        name: buding-service-es
buding:
    elasticsearch:
        hostlist: es.budingcc.cn:9200
eureka:
    client:
        service-url:
            defaultZone: http://budingcc.cn:50000/eureka/
        fetch-registry: true
        register-with-eureka: true
    instance:
        prefer-ip-address: true
        ip-address: budingcc.cn
        instance-id: ${spring.application.name}:${server.port}
    ribbon:
        MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
        MaxAutoRetriesNextServer: 3 #切换实例的重试次数
        OkToRetryOnAllOperations: false #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
        ConnectTimeout: 5000 #请求连接的超时时间
        ReadTimeout: 6000 #请求处理的超时时间
# key uri
security:
    oauth2:
        client:
            client-id: esService
            client-secret: 123456
        resource:
            jwt:
                key-uri: http://oauth.budingcc.cn:40000/oauth/token_key
